const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFileSync } = require("node:child_process");

describe("Protocol generation gate", function () {
  it("checks frozen generated bytes before any mutating generation step", function () {
    const root = path.resolve(__dirname, "..");
    const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
    assert.match(
      packageJson.scripts.verify,
      /^npm run verify:phase1 && npm run protocol:generated:check &&/u,
    );
    assert.equal(
      packageJson.scripts["protocol:check"],
      "npm run protocol:fixture:check && npm --prefix packages/protocol run check",
    );

    const protocolRoot = path.join(root, "packages", "protocol");
    const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), "p2pflow-generation-check-"));
    try {
      for (const relativePath of [
        "package.json",
        "fixtures/local-diamond.abi.json",
        "fixtures/usdc.abi.json",
        "fixtures/local-base-sepolia.manifest.input.json",
        "artifacts/local-diamond.abi.json",
        "artifacts/local-base-sepolia.manifest.json",
        "artifacts/protocol-artifact.json",
        "src/generated/artifacts.ts",
        "scripts/generate.mjs",
      ]) {
        const source = path.join(protocolRoot, relativePath);
        const target = path.join(temporaryRoot, relativePath);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.copyFileSync(source, target);
      }
      const generator = path.join(temporaryRoot, "scripts", "generate.mjs");
      execFileSync(process.execPath, [generator, "--check"], { cwd: temporaryRoot, stdio: "pipe" });
      fs.appendFileSync(path.join(temporaryRoot, "src", "generated", "artifacts.ts"), "// drift\n");
      assert.throws(
        () => execFileSync(process.execPath, [generator, "--check"], { cwd: temporaryRoot, stdio: "pipe" }),
        /Command failed/u,
      );
    } finally {
      fs.rmSync(temporaryRoot, { recursive: true, force: true });
    }
  });
});
