import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));

function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, child]) => [key, canonicalize(child)]),
    );
  }
  return value;
}

const stableStringify = (value) => JSON.stringify(canonicalize(value));
const sha256 = (value) => `0x${crypto.createHash("sha256").update(stableStringify(value)).digest("hex")}`;

const diamondAbi = JSON.parse(fs.readFileSync(path.join(root, "fixtures", "local-diamond.abi.json"), "utf8"));
const usdcAbi = JSON.parse(fs.readFileSync(path.join(root, "fixtures", "usdc.abi.json"), "utf8"));
const manifestInput = JSON.parse(
  fs.readFileSync(path.join(root, "fixtures", "local-base-sepolia.manifest.input.json"), "utf8"),
);

const abiSha256 = sha256(diamondAbi);
const usdcAbiSha256 = sha256(usdcAbi);
const unsignedManifest = { ...manifestInput, abiSha256, usdcAbiSha256 };
const manifest = { ...unsignedManifest, manifestSha256: sha256(unsignedManifest) };
const protocolArtifactDigest = sha256({
  abiSha256,
  manifestSha256: manifest.manifestSha256,
  packageName: packageJson.name,
  packageVersion: packageJson.version,
});
const artifact = {
  packageName: packageJson.name,
  packageVersion: packageJson.version,
  protocolId: manifest.protocolId,
  protocolVersion: manifest.protocolVersion,
  layoutVersion: manifest.layoutVersion,
  storageNamespace: manifest.storageNamespace,
  fixtureKind: manifest.kind,
  deployed: manifest.deployed,
  safeForSharedEnvironment: manifest.safeForSharedEnvironment,
  abiSha256,
  usdcAbiSha256,
  manifestSha256: manifest.manifestSha256,
  protocolArtifactDigest,
};

const outputs = new Map([
  ["artifacts/local-diamond.abi.json", `${JSON.stringify(diamondAbi, null, 2)}\n`],
  ["artifacts/local-base-sepolia.manifest.json", `${JSON.stringify(manifest, null, 2)}\n`],
  ["artifacts/protocol-artifact.json", `${JSON.stringify(artifact, null, 2)}\n`],
  [
    "src/generated/artifacts.ts",
    `// Generated by scripts/generate.mjs. Do not edit.\n` +
      `export const GENERATED_DIAMOND_ABI = ${JSON.stringify(diamondAbi, null, 2)} as const;\n` +
      `export const GENERATED_USDC_ABI = ${JSON.stringify(usdcAbi, null, 2)} as const;\n` +
      `export const GENERATED_LOCAL_BASE_SEPOLIA_FIXTURE = ${JSON.stringify(manifest, null, 2)} as const;\n` +
      `export const GENERATED_PROTOCOL_ARTIFACT = ${JSON.stringify(artifact, null, 2)} as const;\n`,
  ],
]);

for (const [relativePath, content] of outputs) {
  const target = path.join(root, relativePath);
  if (check) {
    if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== content) {
      throw new Error(`${relativePath} has generated drift; run npm run generate`);
    }
    continue;
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content);
}

console.log(check ? "Protocol generated artifacts are current" : "Generated deterministic local protocol artifacts");
