apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-helper-operations-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: order-helper
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              p2pflow.network/operations-monitor: "true"
      ports:
        - protocol: TCP
          port: 8080
